name: Deployment workflow with SA

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed to be able to use the auth token from GCP auth step

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP (SA)
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: gcloud run deploy fastify-api-[INSERT_YOUR_NAME_HERE] --image gcr.io/gcp-competence-group/fastify-api-[INSERT_YOUR_NAME_HERE]:latest --platform managed --region europe-central2